### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Tests.ClientAPI.Embedded.Security
  commentId: N:EventStore.Core.Tests.ClientAPI.Embedded.Security
  id: EventStore.Core.Tests.ClientAPI.Embedded.Security
  children:
  - EventStore.Core.Tests.ClientAPI.Embedded.Security.authorized_default_credentials_security
  langs:
  - csharp
  - vb
  name: EventStore.Core.Tests.ClientAPI.Embedded.Security
  nameWithType: EventStore.Core.Tests.ClientAPI.Embedded.Security
  fullName: EventStore.Core.Tests.ClientAPI.Embedded.Security
  type: Namespace
  assemblies:
  - EventStore.Core.Tests
references:
- uid: EventStore.Core.Tests.ClientAPI.Embedded.Security.authorized_default_credentials_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Embedded.Security.authorized_default_credentials_security
  isExternal: false
  name: authorized_default_credentials_security
  nameWithType: authorized_default_credentials_security
  fullName: EventStore.Core.Tests.ClientAPI.Embedded.Security.authorized_default_credentials_security
