### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Tests.ClientAPI.Security
  commentId: N:EventStore.Core.Tests.ClientAPI.Security
  id: EventStore.Core.Tests.ClientAPI.Security
  children:
  - EventStore.Core.Tests.ClientAPI.Security.all_stream_with_no_acl_security
  - EventStore.Core.Tests.ClientAPI.Security.AuthenticationTestBase
  - EventStore.Core.Tests.ClientAPI.Security.authorized_default_credentials_security
  - EventStore.Core.Tests.ClientAPI.Security.delete_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.multiple_role_security
  - EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security_for_all
  - EventStore.Core.Tests.ClientAPI.Security.overriden_user_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.read_all_security
  - EventStore.Core.Tests.ClientAPI.Security.read_stream_meta_security
  - EventStore.Core.Tests.ClientAPI.Security.read_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.stream_security_inheritance
  - EventStore.Core.Tests.ClientAPI.Security.subscribe_to_all_security
  - EventStore.Core.Tests.ClientAPI.Security.subscribe_to_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.system_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.transactional_write_stream_security
  - EventStore.Core.Tests.ClientAPI.Security.write_stream_meta_security
  - EventStore.Core.Tests.ClientAPI.Security.write_stream_security
  langs:
  - csharp
  - vb
  name: EventStore.Core.Tests.ClientAPI.Security
  nameWithType: EventStore.Core.Tests.ClientAPI.Security
  fullName: EventStore.Core.Tests.ClientAPI.Security
  type: Namespace
  assemblies:
  - EventStore.Core.Tests
references:
- uid: EventStore.Core.Tests.ClientAPI.Security.multiple_role_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.multiple_role_security
  isExternal: false
  name: multiple_role_security
  nameWithType: multiple_role_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.multiple_role_security
- uid: EventStore.Core.Tests.ClientAPI.Security.stream_security_inheritance
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.stream_security_inheritance
  isExternal: false
  name: stream_security_inheritance
  nameWithType: stream_security_inheritance
  fullName: EventStore.Core.Tests.ClientAPI.Security.stream_security_inheritance
- uid: EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security_for_all
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security_for_all
  isExternal: false
  name: overriden_system_stream_security_for_all
  nameWithType: overriden_system_stream_security_for_all
  fullName: EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security_for_all
- uid: EventStore.Core.Tests.ClientAPI.Security.overriden_user_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.overriden_user_stream_security
  isExternal: false
  name: overriden_user_stream_security
  nameWithType: overriden_user_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.overriden_user_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security
  isExternal: false
  name: overriden_system_stream_security
  nameWithType: overriden_system_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.overriden_system_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.all_stream_with_no_acl_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.all_stream_with_no_acl_security
  isExternal: false
  name: all_stream_with_no_acl_security
  nameWithType: all_stream_with_no_acl_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.all_stream_with_no_acl_security
- uid: EventStore.Core.Tests.ClientAPI.Security.delete_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.delete_stream_security
  isExternal: false
  name: delete_stream_security
  nameWithType: delete_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.delete_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.system_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.system_stream_security
  isExternal: false
  name: system_stream_security
  nameWithType: system_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.system_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.read_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.read_stream_security
  isExternal: false
  name: read_stream_security
  nameWithType: read_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.read_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.read_all_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.read_all_security
  isExternal: false
  name: read_all_security
  nameWithType: read_all_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.read_all_security
- uid: EventStore.Core.Tests.ClientAPI.Security.read_stream_meta_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.read_stream_meta_security
  isExternal: false
  name: read_stream_meta_security
  nameWithType: read_stream_meta_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.read_stream_meta_security
- uid: EventStore.Core.Tests.ClientAPI.Security.AuthenticationTestBase
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.AuthenticationTestBase
  parent: EventStore.Core.Tests.ClientAPI.Security
  isExternal: false
  name: AuthenticationTestBase
  nameWithType: AuthenticationTestBase
  fullName: EventStore.Core.Tests.ClientAPI.Security.AuthenticationTestBase
- uid: EventStore.Core.Tests.ClientAPI.Security.authorized_default_credentials_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.authorized_default_credentials_security
  parent: EventStore.Core.Tests.ClientAPI.Security
  isExternal: false
  name: authorized_default_credentials_security
  nameWithType: authorized_default_credentials_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.authorized_default_credentials_security
- uid: EventStore.Core.Tests.ClientAPI.Security.subscribe_to_all_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.subscribe_to_all_security
  isExternal: false
  name: subscribe_to_all_security
  nameWithType: subscribe_to_all_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.subscribe_to_all_security
- uid: EventStore.Core.Tests.ClientAPI.Security.subscribe_to_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.subscribe_to_stream_security
  isExternal: false
  name: subscribe_to_stream_security
  nameWithType: subscribe_to_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.subscribe_to_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.transactional_write_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.transactional_write_stream_security
  isExternal: false
  name: transactional_write_stream_security
  nameWithType: transactional_write_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.transactional_write_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security.write_stream_meta_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.write_stream_meta_security
  isExternal: false
  name: write_stream_meta_security
  nameWithType: write_stream_meta_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.write_stream_meta_security
- uid: EventStore.Core.Tests.ClientAPI.Security.write_stream_security
  commentId: T:EventStore.Core.Tests.ClientAPI.Security.write_stream_security
  isExternal: false
  name: write_stream_security
  nameWithType: write_stream_security
  fullName: EventStore.Core.Tests.ClientAPI.Security.write_stream_security
- uid: EventStore.Core.Tests.ClientAPI.Security
  commentId: N:EventStore.Core.Tests.ClientAPI.Security
  isExternal: false
  name: EventStore.Core.Tests.ClientAPI.Security
  nameWithType: EventStore.Core.Tests.ClientAPI.Security
  fullName: EventStore.Core.Tests.ClientAPI.Security
