### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Settings.ESConsts
  commentId: T:EventStore.Core.Settings.ESConsts
  id: ESConsts
  parent: EventStore.Core.Settings
  children:
  - EventStore.Core.Settings.ESConsts.CachedEpochCount
  - EventStore.Core.Settings.ESConsts.CachedPrincipalCount
  - EventStore.Core.Settings.ESConsts.CommitedEventsMemCacheLimit
  - EventStore.Core.Settings.ESConsts.HttpTimeout
  - EventStore.Core.Settings.ESConsts.MemTableEntryCount
  - EventStore.Core.Settings.ESConsts.PTableInitialReaderCount
  - EventStore.Core.Settings.ESConsts.PTableMaxReaderCount
  - EventStore.Core.Settings.ESConsts.ReadRequestTimeout
  - EventStore.Core.Settings.ESConsts.StorageReaderThreadCount
  - EventStore.Core.Settings.ESConsts.StreamInfoCacheCapacity
  - EventStore.Core.Settings.ESConsts.TFChunkMaxReaderCount
  - EventStore.Core.Settings.ESConsts.TransactionMetadataCacheCapacity
  - EventStore.Core.Settings.ESConsts.UnrestrictedPendingSendBytes
  langs:
  - csharp
  - vb
  name: ESConsts
  nameWithType: ESConsts
  fullName: EventStore.Core.Settings.ESConsts
  type: Class
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: ESConsts
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 4
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: 'public static class ESConsts : object'
    content.vb: >-
      Public Module ESConsts
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: EventStore.Core.Settings.ESConsts.StorageReaderThreadCount
  commentId: F:EventStore.Core.Settings.ESConsts.StorageReaderThreadCount
  id: StorageReaderThreadCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: StorageReaderThreadCount
  nameWithType: ESConsts.StorageReaderThreadCount
  fullName: EventStore.Core.Settings.ESConsts.StorageReaderThreadCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: StorageReaderThreadCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 6
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int StorageReaderThreadCount = null
    return:
      type: System.Int32
    content.vb: Public Const StorageReaderThreadCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.PTableInitialReaderCount
  commentId: F:EventStore.Core.Settings.ESConsts.PTableInitialReaderCount
  id: PTableInitialReaderCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: PTableInitialReaderCount
  nameWithType: ESConsts.PTableInitialReaderCount
  fullName: EventStore.Core.Settings.ESConsts.PTableInitialReaderCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: PTableInitialReaderCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 8
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int PTableInitialReaderCount = null
    return:
      type: System.Int32
    content.vb: Public Const PTableInitialReaderCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.PTableMaxReaderCount
  commentId: F:EventStore.Core.Settings.ESConsts.PTableMaxReaderCount
  id: PTableMaxReaderCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: PTableMaxReaderCount
  nameWithType: ESConsts.PTableMaxReaderCount
  fullName: EventStore.Core.Settings.ESConsts.PTableMaxReaderCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: PTableMaxReaderCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 9
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int PTableMaxReaderCount = null
    return:
      type: System.Int32
    content.vb: Public Const PTableMaxReaderCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.TFChunkMaxReaderCount
  commentId: F:EventStore.Core.Settings.ESConsts.TFChunkMaxReaderCount
  id: TFChunkMaxReaderCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: TFChunkMaxReaderCount
  nameWithType: ESConsts.TFChunkMaxReaderCount
  fullName: EventStore.Core.Settings.ESConsts.TFChunkMaxReaderCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: TFChunkMaxReaderCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 17
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int TFChunkMaxReaderCount = null
    return:
      type: System.Int32
    content.vb: Public Const TFChunkMaxReaderCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.MemTableEntryCount
  commentId: F:EventStore.Core.Settings.ESConsts.MemTableEntryCount
  id: MemTableEntryCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: MemTableEntryCount
  nameWithType: ESConsts.MemTableEntryCount
  fullName: EventStore.Core.Settings.ESConsts.MemTableEntryCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: MemTableEntryCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 22
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int MemTableEntryCount = null
    return:
      type: System.Int32
    content.vb: Public Const MemTableEntryCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.StreamInfoCacheCapacity
  commentId: F:EventStore.Core.Settings.ESConsts.StreamInfoCacheCapacity
  id: StreamInfoCacheCapacity
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: StreamInfoCacheCapacity
  nameWithType: ESConsts.StreamInfoCacheCapacity
  fullName: EventStore.Core.Settings.ESConsts.StreamInfoCacheCapacity
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: StreamInfoCacheCapacity
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 23
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int StreamInfoCacheCapacity = null
    return:
      type: System.Int32
    content.vb: Public Const StreamInfoCacheCapacity As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.TransactionMetadataCacheCapacity
  commentId: F:EventStore.Core.Settings.ESConsts.TransactionMetadataCacheCapacity
  id: TransactionMetadataCacheCapacity
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: TransactionMetadataCacheCapacity
  nameWithType: ESConsts.TransactionMetadataCacheCapacity
  fullName: EventStore.Core.Settings.ESConsts.TransactionMetadataCacheCapacity
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: TransactionMetadataCacheCapacity
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 24
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int TransactionMetadataCacheCapacity = null
    return:
      type: System.Int32
    content.vb: Public Const TransactionMetadataCacheCapacity As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.CommitedEventsMemCacheLimit
  commentId: F:EventStore.Core.Settings.ESConsts.CommitedEventsMemCacheLimit
  id: CommitedEventsMemCacheLimit
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: CommitedEventsMemCacheLimit
  nameWithType: ESConsts.CommitedEventsMemCacheLimit
  fullName: EventStore.Core.Settings.ESConsts.CommitedEventsMemCacheLimit
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: CommitedEventsMemCacheLimit
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 25
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int CommitedEventsMemCacheLimit = null
    return:
      type: System.Int32
    content.vb: Public Const CommitedEventsMemCacheLimit As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.CachedEpochCount
  commentId: F:EventStore.Core.Settings.ESConsts.CachedEpochCount
  id: CachedEpochCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: CachedEpochCount
  nameWithType: ESConsts.CachedEpochCount
  fullName: EventStore.Core.Settings.ESConsts.CachedEpochCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: CachedEpochCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 26
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int CachedEpochCount = null
    return:
      type: System.Int32
    content.vb: Public Const CachedEpochCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.ReadRequestTimeout
  commentId: F:EventStore.Core.Settings.ESConsts.ReadRequestTimeout
  id: ReadRequestTimeout
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: ReadRequestTimeout
  nameWithType: ESConsts.ReadRequestTimeout
  fullName: EventStore.Core.Settings.ESConsts.ReadRequestTimeout
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: ReadRequestTimeout
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 27
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int ReadRequestTimeout = null
    return:
      type: System.Int32
    content.vb: Public Const ReadRequestTimeout As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.CachedPrincipalCount
  commentId: F:EventStore.Core.Settings.ESConsts.CachedPrincipalCount
  id: CachedPrincipalCount
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: CachedPrincipalCount
  nameWithType: ESConsts.CachedPrincipalCount
  fullName: EventStore.Core.Settings.ESConsts.CachedPrincipalCount
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: CachedPrincipalCount
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 29
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int CachedPrincipalCount = null
    return:
      type: System.Int32
    content.vb: Public Const CachedPrincipalCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Settings.ESConsts.HttpTimeout
  commentId: F:EventStore.Core.Settings.ESConsts.HttpTimeout
  id: HttpTimeout
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: HttpTimeout
  nameWithType: ESConsts.HttpTimeout
  fullName: EventStore.Core.Settings.ESConsts.HttpTimeout
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: HttpTimeout
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 31
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public static readonly TimeSpan HttpTimeout
    return:
      type: TimeSpan
    content.vb: Public Shared ReadOnly HttpTimeout As TimeSpan
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: EventStore.Core.Settings.ESConsts.UnrestrictedPendingSendBytes
  commentId: F:EventStore.Core.Settings.ESConsts.UnrestrictedPendingSendBytes
  id: UnrestrictedPendingSendBytes
  parent: EventStore.Core.Settings.ESConsts
  langs:
  - csharp
  - vb
  name: UnrestrictedPendingSendBytes
  nameWithType: ESConsts.UnrestrictedPendingSendBytes
  fullName: EventStore.Core.Settings.ESConsts.UnrestrictedPendingSendBytes
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Settings/ESConsts.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: UnrestrictedPendingSendBytes
    path: ../EventStore/src/EventStore.Core/Settings/ESConsts.cs
    startLine: 33
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Settings
  syntax:
    content: public const int UnrestrictedPendingSendBytes = null
    return:
      type: System.Int32
    content.vb: Public Const UnrestrictedPendingSendBytes As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: EventStore.Core.Settings
  commentId: N:EventStore.Core.Settings
  isExternal: false
  name: EventStore.Core.Settings
  nameWithType: EventStore.Core.Settings
  fullName: EventStore.Core.Settings
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: TimeSpan
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: TimeSpan
