### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Settings
  commentId: N:EventStore.Core.Settings
  id: EventStore.Core.Settings
  children:
  - EventStore.Core.Settings.ESConsts
  - EventStore.Core.Settings.SingleVNodeSettings
  langs:
  - csharp
  - vb
  name: EventStore.Core.Settings
  nameWithType: EventStore.Core.Settings
  fullName: EventStore.Core.Settings
  type: Namespace
  assemblies:
  - EventStore.Core
references:
- uid: EventStore.Core.Settings.ESConsts
  commentId: T:EventStore.Core.Settings.ESConsts
  name: ESConsts
  nameWithType: ESConsts
  fullName: EventStore.Core.Settings.ESConsts
- uid: EventStore.Core.Settings.SingleVNodeSettings
  commentId: T:EventStore.Core.Settings.SingleVNodeSettings
  name: SingleVNodeSettings
  nameWithType: SingleVNodeSettings
  fullName: EventStore.Core.Settings.SingleVNodeSettings
