### YamlMime:ManagedReference
items:
- uid: EventStore.Transport.Tcp.TcpConfiguration
  commentId: T:EventStore.Transport.Tcp.TcpConfiguration
  id: TcpConfiguration
  parent: EventStore.Transport.Tcp
  children:
  - EventStore.Transport.Tcp.TcpConfiguration.AcceptBacklogCount
  - EventStore.Transport.Tcp.TcpConfiguration.AcceptPoolSize
  - EventStore.Transport.Tcp.TcpConfiguration.BufferChunksCount
  - EventStore.Transport.Tcp.TcpConfiguration.ConcurrentAccepts
  - EventStore.Transport.Tcp.TcpConfiguration.ConnectPoolSize
  - EventStore.Transport.Tcp.TcpConfiguration.SendReceivePoolSize
  - EventStore.Transport.Tcp.TcpConfiguration.SocketBufferSize
  - EventStore.Transport.Tcp.TcpConfiguration.SocketCloseTimeoutMs
  langs:
  - csharp
  - vb
  name: TcpConfiguration
  nameWithType: TcpConfiguration
  fullName: EventStore.Transport.Tcp.TcpConfiguration
  type: Class
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: TcpConfiguration
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 2
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: 'public static class TcpConfiguration : object'
    content.vb: >-
      Public Module TcpConfiguration

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: EventStore.Transport.Tcp.TcpConfiguration.SocketCloseTimeoutMs
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.SocketCloseTimeoutMs
  id: SocketCloseTimeoutMs
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: SocketCloseTimeoutMs
  nameWithType: TcpConfiguration.SocketCloseTimeoutMs
  fullName: EventStore.Transport.Tcp.TcpConfiguration.SocketCloseTimeoutMs
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: SocketCloseTimeoutMs
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 4
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int SocketCloseTimeoutMs = null
    return:
      type: System.Int32
    content.vb: Public Const SocketCloseTimeoutMs As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.AcceptBacklogCount
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.AcceptBacklogCount
  id: AcceptBacklogCount
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: AcceptBacklogCount
  nameWithType: TcpConfiguration.AcceptBacklogCount
  fullName: EventStore.Transport.Tcp.TcpConfiguration.AcceptBacklogCount
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: AcceptBacklogCount
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 6
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int AcceptBacklogCount = null
    return:
      type: System.Int32
    content.vb: Public Const AcceptBacklogCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.ConcurrentAccepts
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.ConcurrentAccepts
  id: ConcurrentAccepts
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: ConcurrentAccepts
  nameWithType: TcpConfiguration.ConcurrentAccepts
  fullName: EventStore.Transport.Tcp.TcpConfiguration.ConcurrentAccepts
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: ConcurrentAccepts
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 7
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int ConcurrentAccepts = null
    return:
      type: System.Int32
    content.vb: Public Const ConcurrentAccepts As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.AcceptPoolSize
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.AcceptPoolSize
  id: AcceptPoolSize
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: AcceptPoolSize
  nameWithType: TcpConfiguration.AcceptPoolSize
  fullName: EventStore.Transport.Tcp.TcpConfiguration.AcceptPoolSize
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: AcceptPoolSize
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 8
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int AcceptPoolSize = null
    return:
      type: System.Int32
    content.vb: Public Const AcceptPoolSize As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.ConnectPoolSize
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.ConnectPoolSize
  id: ConnectPoolSize
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: ConnectPoolSize
  nameWithType: TcpConfiguration.ConnectPoolSize
  fullName: EventStore.Transport.Tcp.TcpConfiguration.ConnectPoolSize
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: ConnectPoolSize
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 10
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int ConnectPoolSize = null
    return:
      type: System.Int32
    content.vb: Public Const ConnectPoolSize As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.SendReceivePoolSize
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.SendReceivePoolSize
  id: SendReceivePoolSize
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: SendReceivePoolSize
  nameWithType: TcpConfiguration.SendReceivePoolSize
  fullName: EventStore.Transport.Tcp.TcpConfiguration.SendReceivePoolSize
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: SendReceivePoolSize
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 11
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int SendReceivePoolSize = null
    return:
      type: System.Int32
    content.vb: Public Const SendReceivePoolSize As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.BufferChunksCount
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.BufferChunksCount
  id: BufferChunksCount
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: BufferChunksCount
  nameWithType: TcpConfiguration.BufferChunksCount
  fullName: EventStore.Transport.Tcp.TcpConfiguration.BufferChunksCount
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: BufferChunksCount
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 13
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int BufferChunksCount = null
    return:
      type: System.Int32
    content.vb: Public Const BufferChunksCount As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Tcp.TcpConfiguration.SocketBufferSize
  commentId: F:EventStore.Transport.Tcp.TcpConfiguration.SocketBufferSize
  id: SocketBufferSize
  parent: EventStore.Transport.Tcp.TcpConfiguration
  langs:
  - csharp
  - vb
  name: SocketBufferSize
  nameWithType: TcpConfiguration.SocketBufferSize
  fullName: EventStore.Transport.Tcp.TcpConfiguration.SocketBufferSize
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Tcp/TcpConfiguration.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: SocketBufferSize
    path: ../EventStore/src/EventStore.Transport.Tcp/TcpConfiguration.cs
    startLine: 14
  assemblies:
  - EventStore.Transport.Tcp
  namespace: EventStore.Transport.Tcp
  syntax:
    content: public const int SocketBufferSize = null
    return:
      type: System.Int32
    content.vb: Public Const SocketBufferSize As Integer = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: EventStore.Transport.Tcp
  commentId: N:EventStore.Transport.Tcp
  isExternal: false
  name: EventStore.Transport.Tcp
  nameWithType: EventStore.Transport.Tcp
  fullName: EventStore.Transport.Tcp
- uid: System.Object
  commentId: T:System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
