### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Cluster.Settings
  commentId: N:EventStore.Core.Cluster.Settings
  id: EventStore.Core.Cluster.Settings
  children:
  - EventStore.Core.Cluster.Settings.ClusterConsts
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  - EventStore.Core.Cluster.Settings.ClusterVNodeSettings
  langs:
  - csharp
  - vb
  name: EventStore.Core.Cluster.Settings
  nameWithType: EventStore.Core.Cluster.Settings
  fullName: EventStore.Core.Cluster.Settings
  type: Namespace
  assemblies:
  - EventStore.Core
references:
- uid: EventStore.Core.Cluster.Settings.ClusterConsts
  commentId: T:EventStore.Core.Cluster.Settings.ClusterConsts
  isExternal: false
  name: ClusterConsts
  nameWithType: ClusterConsts
  fullName: EventStore.Core.Cluster.Settings.ClusterConsts
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  commentId: T:EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  parent: EventStore.Core.Cluster.Settings
  isExternal: false
  name: ClusterVNodeAuthenticationType
  nameWithType: ClusterVNodeAuthenticationType
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeSettings
  commentId: T:EventStore.Core.Cluster.Settings.ClusterVNodeSettings
  parent: EventStore.Core.Cluster.Settings
  isExternal: false
  name: ClusterVNodeSettings
  nameWithType: ClusterVNodeSettings
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeSettings
- uid: EventStore.Core.Cluster.Settings
  commentId: N:EventStore.Core.Cluster.Settings
  isExternal: false
  name: EventStore.Core.Cluster.Settings
  nameWithType: EventStore.Core.Cluster.Settings
  fullName: EventStore.Core.Cluster.Settings
