### YamlMime:ManagedReference
items:
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  commentId: T:EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  id: ClusterVNodeAuthenticationType
  parent: EventStore.Core.Cluster.Settings
  children:
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Internal
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Ldaps
  langs:
  - csharp
  - vb
  name: ClusterVNodeAuthenticationType
  nameWithType: ClusterVNodeAuthenticationType
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  type: Enum
  source:
    remote:
      path: src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
      branch: release-v4.1.1
      repo: https://github.com/EventStore/EventStore.git
    id: ClusterVNodeAuthenticationType
    path: ../EventStore/src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
    startLine: 2
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Cluster.Settings
  syntax:
    content: 'public enum ClusterVNodeAuthenticationType : int'
    content.vb: Public Enum ClusterVNodeAuthenticationType As Integer
  extensionMethods:
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1
  - EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Internal
  commentId: F:EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Internal
  id: Internal
  parent: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  langs:
  - csharp
  - vb
  name: Internal
  nameWithType: ClusterVNodeAuthenticationType.Internal
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Internal
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
      branch: release-v4.1.1
      repo: https://github.com/EventStore/EventStore.git
    id: Internal
    path: ../EventStore/src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
    startLine: 4
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Cluster.Settings
  syntax:
    content: Internal = 0
    return:
      type: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Ldaps
  commentId: F:EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Ldaps
  id: Ldaps
  parent: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  langs:
  - csharp
  - vb
  name: Ldaps
  nameWithType: ClusterVNodeAuthenticationType.Ldaps
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.Ldaps
  type: Field
  source:
    remote:
      path: src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
      branch: release-v4.1.1
      repo: https://github.com/EventStore/EventStore.git
    id: Ldaps
    path: ../EventStore/src/EventStore.Core/Cluster/Settings/ClusterVNodeAuthenticationType.cs
    startLine: 5
  assemblies:
  - EventStore.Core
  namespace: EventStore.Core.Cluster.Settings
  syntax:
    content: Ldaps = 1
    return:
      type: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: EventStore.Core.Cluster.Settings
  commentId: N:EventStore.Core.Cluster.Settings
  isExternal: false
  name: EventStore.Core.Cluster.Settings
  nameWithType: EventStore.Core.Cluster.Settings
  fullName: EventStore.Core.Cluster.Settings
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1
  commentId: M:EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
  parent: EventStore.Projections.Core.Utils.EnumExtensions
  definition: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
  name: EnumValueName<ClusterVNodeAuthenticationType>()
  nameWithType: EnumExtensions.EnumValueName<ClusterVNodeAuthenticationType>()
  fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>()
  nameWithType.vb: EnumExtensions.EnumValueName(Of ClusterVNodeAuthenticationType)()
  fullName.vb: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)()
  name.vb: EnumValueName(Of ClusterVNodeAuthenticationType)()
  spec.csharp:
  - uid: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1
    name: EnumValueName<ClusterVNodeAuthenticationType>
    nameWithType: EnumExtensions.EnumValueName<ClusterVNodeAuthenticationType>
    fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1
    name: EnumValueName(Of ClusterVNodeAuthenticationType)
    nameWithType: EnumExtensions.EnumValueName(Of ClusterVNodeAuthenticationType)
    fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1
  commentId: M:EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
  parent: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions
  definition: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
  name: Serialize<ClusterVNodeAuthenticationType>()
  nameWithType: ProtobufExtensions.Serialize<ClusterVNodeAuthenticationType>()
  fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>()
  nameWithType.vb: ProtobufExtensions.Serialize(Of ClusterVNodeAuthenticationType)()
  fullName.vb: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)()
  name.vb: Serialize(Of ClusterVNodeAuthenticationType)()
  spec.csharp:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1
    name: Serialize<ClusterVNodeAuthenticationType>
    nameWithType: ProtobufExtensions.Serialize<ClusterVNodeAuthenticationType>
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1
    name: Serialize(Of ClusterVNodeAuthenticationType)
    nameWithType: ProtobufExtensions.Serialize(Of ClusterVNodeAuthenticationType)
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType.EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1
  commentId: M:EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
  parent: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions
  definition: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
  name: SerializeToArray<ClusterVNodeAuthenticationType>()
  nameWithType: ProtobufExtensions.SerializeToArray<ClusterVNodeAuthenticationType>()
  fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>()
  nameWithType.vb: ProtobufExtensions.SerializeToArray(Of ClusterVNodeAuthenticationType)()
  fullName.vb: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)()
  name.vb: SerializeToArray(Of ClusterVNodeAuthenticationType)()
  spec.csharp:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1
    name: SerializeToArray<ClusterVNodeAuthenticationType>
    nameWithType: ProtobufExtensions.SerializeToArray<ClusterVNodeAuthenticationType>
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray<EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1
    name: SerializeToArray(Of ClusterVNodeAuthenticationType)
    nameWithType: ProtobufExtensions.SerializeToArray(Of ClusterVNodeAuthenticationType)
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray(Of EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
  commentId: M:EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
  isExternal: false
  name: EnumValueName<T>(T)
  nameWithType: EnumExtensions.EnumValueName<T>(T)
  fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName<T>(T)
  nameWithType.vb: EnumExtensions.EnumValueName(Of T)(T)
  fullName.vb: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName(Of T)(T)
  name.vb: EnumValueName(Of T)(T)
  spec.csharp:
  - uid: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
    name: EnumValueName<T>
    nameWithType: EnumExtensions.EnumValueName<T>
    fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName``1(``0)
    name: EnumValueName(Of T)
    nameWithType: EnumExtensions.EnumValueName(Of T)
    fullName: EventStore.Projections.Core.Utils.EnumExtensions.EnumValueName(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Utils.EnumExtensions
  commentId: T:EventStore.Projections.Core.Utils.EnumExtensions
  parent: EventStore.Projections.Core.Utils
  isExternal: false
  name: EnumExtensions
  nameWithType: EnumExtensions
  fullName: EventStore.Projections.Core.Utils.EnumExtensions
- uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
  commentId: M:EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
  isExternal: false
  name: Serialize<T>(T)
  nameWithType: ProtobufExtensions.Serialize<T>(T)
  fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize<T>(T)
  nameWithType.vb: ProtobufExtensions.Serialize(Of T)(T)
  fullName.vb: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize(Of T)(T)
  name.vb: Serialize(Of T)(T)
  spec.csharp:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
    name: Serialize<T>
    nameWithType: ProtobufExtensions.Serialize<T>
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize``1(``0)
    name: Serialize(Of T)
    nameWithType: ProtobufExtensions.Serialize(Of T)
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Serialize(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions
  commentId: T:EventStore.Core.Services.Transport.Tcp.ProtobufExtensions
  parent: EventStore.Core.Services.Transport.Tcp
  isExternal: false
  name: ProtobufExtensions
  nameWithType: ProtobufExtensions
  fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions
- uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
  commentId: M:EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
  isExternal: false
  name: SerializeToArray<T>(T)
  nameWithType: ProtobufExtensions.SerializeToArray<T>(T)
  fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray<T>(T)
  nameWithType.vb: ProtobufExtensions.SerializeToArray(Of T)(T)
  fullName.vb: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray(Of T)(T)
  name.vb: SerializeToArray(Of T)(T)
  spec.csharp:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
    name: SerializeToArray<T>
    nameWithType: ProtobufExtensions.SerializeToArray<T>
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray``1(``0)
    name: SerializeToArray(Of T)
    nameWithType: ProtobufExtensions.SerializeToArray(Of T)
    fullName: EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.SerializeToArray(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Utils
  commentId: N:EventStore.Projections.Core.Utils
  isExternal: false
  name: EventStore.Projections.Core.Utils
  nameWithType: EventStore.Projections.Core.Utils
  fullName: EventStore.Projections.Core.Utils
- uid: EventStore.Core.Services.Transport.Tcp
  commentId: N:EventStore.Core.Services.Transport.Tcp
  isExternal: false
  name: EventStore.Core.Services.Transport.Tcp
  nameWithType: EventStore.Core.Services.Transport.Tcp
  fullName: EventStore.Core.Services.Transport.Tcp
- uid: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  commentId: T:EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
  parent: EventStore.Core.Cluster.Settings
  isExternal: false
  name: ClusterVNodeAuthenticationType
  nameWithType: ClusterVNodeAuthenticationType
  fullName: EventStore.Core.Cluster.Settings.ClusterVNodeAuthenticationType
