### YamlMime:ManagedReference
items:
- uid: EventStore.ClientAPI.ClusterSettingsBuilder
  commentId: T:EventStore.ClientAPI.ClusterSettingsBuilder
  id: ClusterSettingsBuilder
  parent: EventStore.ClientAPI
  children:
  - EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns
  - EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
  langs:
  - csharp
  - vb
  name: ClusterSettingsBuilder
  nameWithType: ClusterSettingsBuilder
  fullName: EventStore.ClientAPI.ClusterSettingsBuilder
  type: Class
  source:
    remote:
      path: src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: ClusterSettingsBuilder
    path: ../EventStore/src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
    startLine: 4
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nBuilder used for creating instances of ClusterSettings.\n"
  example: []
  syntax:
    content: 'public class ClusterSettingsBuilder : object'
    content.vb: >-
      Public Class ClusterSettingsBuilder
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns
  commentId: M:EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns
  id: DiscoverClusterViaDns
  parent: EventStore.ClientAPI.ClusterSettingsBuilder
  langs:
  - csharp
  - vb
  name: DiscoverClusterViaDns()
  nameWithType: ClusterSettingsBuilder.DiscoverClusterViaDns()
  fullName: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns()
  type: Method
  source:
    remote:
      path: src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: DiscoverClusterViaDns
    path: ../EventStore/src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
    startLine: 9
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nSets the client to discover nodes using a DNS name and a well-known port.\n"
  example: []
  syntax:
    content: public DnsClusterSettingsBuilder DiscoverClusterViaDns()
    return:
      type: EventStore.ClientAPI.DnsClusterSettingsBuilder
      description: A <xref href="EventStore.ClientAPI.DnsClusterSettingsBuilder" data-throw-if-not-resolved="false"></xref> for further configuration.
    content.vb: Public Function DiscoverClusterViaDns As DnsClusterSettingsBuilder
  overload: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
  commentId: M:EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
  id: DiscoverClusterViaGossipSeeds
  parent: EventStore.ClientAPI.ClusterSettingsBuilder
  langs:
  - csharp
  - vb
  name: DiscoverClusterViaGossipSeeds()
  nameWithType: ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds()
  fullName: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds()
  type: Method
  source:
    remote:
      path: src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: DiscoverClusterViaGossipSeeds
    path: ../EventStore/src/EventStore.ClientAPI/ClusterSettingsBuilder.cs
    startLine: 18
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nSets the client to discover cluster nodes by specifying the IP endpoints of\none or more of the nodes.\n"
  example: []
  syntax:
    content: public GossipSeedClusterSettingsBuilder DiscoverClusterViaGossipSeeds()
    return:
      type: EventStore.ClientAPI.GossipSeedClusterSettingsBuilder
      description: ''
    content.vb: Public Function DiscoverClusterViaGossipSeeds As GossipSeedClusterSettingsBuilder
  overload: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: EventStore.ClientAPI
  commentId: N:EventStore.ClientAPI
  name: EventStore.ClientAPI
  nameWithType: EventStore.ClientAPI
  fullName: EventStore.ClientAPI
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.ClientAPI.DnsClusterSettingsBuilder
  commentId: T:EventStore.ClientAPI.DnsClusterSettingsBuilder
  parent: EventStore.ClientAPI
  name: DnsClusterSettingsBuilder
  nameWithType: DnsClusterSettingsBuilder
  fullName: EventStore.ClientAPI.DnsClusterSettingsBuilder
- uid: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns*
  commentId: Overload:EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns
  name: DiscoverClusterViaDns
  nameWithType: ClusterSettingsBuilder.DiscoverClusterViaDns
  fullName: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaDns
- uid: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds*
  commentId: Overload:EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
  name: DiscoverClusterViaGossipSeeds
  nameWithType: ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
  fullName: EventStore.ClientAPI.ClusterSettingsBuilder.DiscoverClusterViaGossipSeeds
- uid: EventStore.ClientAPI.GossipSeedClusterSettingsBuilder
  commentId: T:EventStore.ClientAPI.GossipSeedClusterSettingsBuilder
  parent: EventStore.ClientAPI
  name: GossipSeedClusterSettingsBuilder
  nameWithType: GossipSeedClusterSettingsBuilder
  fullName: EventStore.ClientAPI.GossipSeedClusterSettingsBuilder
