### YamlMime:ManagedReference
items:
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  commentId: T:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  id: ProjectionsController.ProjectionConfigData
  parent: EventStore.Projections.Core.Services.Http
  children:
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  - EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  langs:
  - csharp
  - vb
  name: ProjectionsController.ProjectionConfigData
  nameWithType: ProjectionsController.ProjectionConfigData
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  type: Class
  source:
    id: ProjectionConfigData
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 627
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: 'public class ProjectionConfigData : object'
    content.vb: >-
      Public Class ProjectionConfigData
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
  id: EmitEnabled
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: EmitEnabled
  nameWithType: ProjectionsController.ProjectionConfigData.EmitEnabled
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
  type: Property
  source:
    id: EmitEnabled
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 628
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public bool EmitEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property EmitEnabled As Boolean
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  id: TrackEmittedStreams
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: TrackEmittedStreams
  nameWithType: ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  type: Property
  source:
    id: TrackEmittedStreams
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 629
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public bool TrackEmittedStreams { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property TrackEmittedStreams As Boolean
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  id: CheckpointAfterMs
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: CheckpointAfterMs
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  type: Property
  source:
    id: CheckpointAfterMs
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 630
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int CheckpointAfterMs { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property CheckpointAfterMs As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  id: CheckpointHandledThreshold
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: CheckpointHandledThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  type: Property
  source:
    id: CheckpointHandledThreshold
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 631
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int CheckpointHandledThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property CheckpointHandledThreshold As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  id: CheckpointUnhandledBytesThreshold
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: CheckpointUnhandledBytesThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  type: Property
  source:
    id: CheckpointUnhandledBytesThreshold
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 632
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int CheckpointUnhandledBytesThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property CheckpointUnhandledBytesThreshold As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  id: PendingEventsThreshold
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: PendingEventsThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  type: Property
  source:
    id: PendingEventsThreshold
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 633
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int PendingEventsThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property PendingEventsThreshold As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  id: MaxWriteBatchLength
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: MaxWriteBatchLength
  nameWithType: ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  type: Property
  source:
    id: MaxWriteBatchLength
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 634
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int MaxWriteBatchLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxWriteBatchLength As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  commentId: P:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  id: MaxAllowedWritesInFlight
  parent: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData
  langs:
  - csharp
  - vb
  name: MaxAllowedWritesInFlight
  nameWithType: ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  type: Property
  source:
    id: MaxAllowedWritesInFlight
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs
    startLine: 635
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Http
  syntax:
    content: public int MaxAllowedWritesInFlight { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxAllowedWritesInFlight As Integer
  overload: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: EventStore.Projections.Core.Services.Http
  commentId: N:EventStore.Projections.Core.Services.Http
  name: EventStore.Projections.Core.Services.Http
  nameWithType: EventStore.Projections.Core.Services.Http
  fullName: EventStore.Projections.Core.Services.Http
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
  name: EmitEnabled
  nameWithType: ProjectionsController.ProjectionConfigData.EmitEnabled
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.EmitEnabled
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  name: TrackEmittedStreams
  nameWithType: ProjectionsController.ProjectionConfigData.TrackEmittedStreams
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.TrackEmittedStreams
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  name: CheckpointAfterMs
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointAfterMs
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointAfterMs
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  name: CheckpointHandledThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointHandledThreshold
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  name: CheckpointUnhandledBytesThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.CheckpointUnhandledBytesThreshold
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  name: PendingEventsThreshold
  nameWithType: ProjectionsController.ProjectionConfigData.PendingEventsThreshold
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.PendingEventsThreshold
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  name: MaxWriteBatchLength
  nameWithType: ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxWriteBatchLength
- uid: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight*
  commentId: Overload:EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  name: MaxAllowedWritesInFlight
  nameWithType: ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
  fullName: EventStore.Projections.Core.Services.Http.ProjectionsController.ProjectionConfigData.MaxAllowedWritesInFlight
