### YamlMime:ManagedReference
items:
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  commentId: T:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  id: ProjectionManagementMessage.Command.GetConfig
  parent: EventStore.Projections.Core.Messages
  children:
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor(EventStore.Core.Messaging.IEnvelope,System.String,EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs)
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
  langs:
  - csharp
  - vb
  name: ProjectionManagementMessage.Command.GetConfig
  nameWithType: ProjectionManagementMessage.Command.GetConfig
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  type: Class
  source:
    id: GetConfig
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Messages/ProjectionManagementMessage.cs
    startLine: 381
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Messages
  syntax:
    content: 'public class GetConfig : ProjectionManagementMessage.Command.ControlMessage'
    content.vb: >-
      Public Class GetConfig

          Inherits ProjectionManagementMessage.Command.ControlMessage
  inheritance:
  - System.Object
  - EventStore.Core.Messaging.Message
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  inheritedMembers:
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.RunAs
  - EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.Envelope
  - EventStore.Core.Messaging.Message.NextMsgId
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  commentId: P:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  id: MsgTypeId
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  langs:
  - csharp
  - vb
  name: MsgTypeId
  nameWithType: ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  type: Property
  source:
    id: MsgTypeId
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Messages/ProjectionManagementMessage.cs
    startLine: 384
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Messages
  syntax:
    content: public override int MsgTypeId { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overrides ReadOnly Property MsgTypeId As Integer
  overridden: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.MsgTypeId
  overload: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId*
  modifiers.csharp:
  - public
  - override
  - get
  modifiers.vb:
  - Public
  - Overrides
  - ReadOnly
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor(EventStore.Core.Messaging.IEnvelope,System.String,EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs)
  commentId: M:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor(EventStore.Core.Messaging.IEnvelope,System.String,EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs)
  id: '#ctor(EventStore.Core.Messaging.IEnvelope,System.String,EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs)'
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  langs:
  - csharp
  - vb
  name: GetConfig(IEnvelope, String, ProjectionManagementMessage.RunAs)
  nameWithType: ProjectionManagementMessage.Command.GetConfig.GetConfig(IEnvelope, String, ProjectionManagementMessage.RunAs)
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.GetConfig(EventStore.Core.Messaging.IEnvelope, System.String, EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs)
  type: Constructor
  source:
    id: .ctor
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Messages/ProjectionManagementMessage.cs
    startLine: 390
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Messages
  syntax:
    content: public GetConfig(IEnvelope envelope, string name, ProjectionManagementMessage.RunAs runAs)
    parameters:
    - id: envelope
      type: EventStore.Core.Messaging.IEnvelope
    - id: name
      type: System.String
    - id: runAs
      type: EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs
    content.vb: Public Sub New(envelope As IEnvelope, name As String, runAs As ProjectionManagementMessage.RunAs)
  overload: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
  commentId: P:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
  id: Name
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ProjectionManagementMessage.Command.GetConfig.Name
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
  type: Property
  source:
    id: Name
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Messages/ProjectionManagementMessage.cs
    startLine: 395
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Messages
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: EventStore.Projections.Core.Messages
  commentId: N:EventStore.Projections.Core.Messages
  name: EventStore.Projections.Core.Messages
  nameWithType: EventStore.Projections.Core.Messages
  fullName: EventStore.Projections.Core.Messages
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.Core.Messaging.Message
  commentId: T:EventStore.Core.Messaging.Message
  parent: EventStore.Core.Messaging
  name: Message
  nameWithType: Message
  fullName: EventStore.Core.Messaging.Message
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  commentId: T:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  parent: EventStore.Projections.Core.Messages
  name: ProjectionManagementMessage.Command.ControlMessage
  nameWithType: ProjectionManagementMessage.Command.ControlMessage
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.RunAs
  commentId: F:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.RunAs
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  name: RunAs
  nameWithType: ProjectionManagementMessage.Command.ControlMessage.RunAs
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.RunAs
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.Envelope
  commentId: P:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.Envelope
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  name: Envelope
  nameWithType: ProjectionManagementMessage.Command.ControlMessage.Envelope
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.Envelope
- uid: EventStore.Core.Messaging.Message.NextMsgId
  commentId: F:EventStore.Core.Messaging.Message.NextMsgId
  parent: EventStore.Core.Messaging.Message
  name: NextMsgId
  nameWithType: Message.NextMsgId
  fullName: EventStore.Core.Messaging.Message.NextMsgId
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EventStore.Core.Messaging
  commentId: N:EventStore.Core.Messaging
  name: EventStore.Core.Messaging
  nameWithType: EventStore.Core.Messaging
  fullName: EventStore.Core.Messaging
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.MsgTypeId
  commentId: P:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.MsgTypeId
  parent: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage
  name: MsgTypeId
  nameWithType: ProjectionManagementMessage.Command.ControlMessage.MsgTypeId
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.ControlMessage.MsgTypeId
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId*
  commentId: Overload:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  name: MsgTypeId
  nameWithType: ProjectionManagementMessage.Command.GetConfig.MsgTypeId
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.MsgTypeId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor*
  commentId: Overload:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.#ctor
  name: GetConfig
  nameWithType: ProjectionManagementMessage.Command.GetConfig.GetConfig
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.GetConfig
- uid: EventStore.Core.Messaging.IEnvelope
  commentId: T:EventStore.Core.Messaging.IEnvelope
  parent: EventStore.Core.Messaging
  name: IEnvelope
  nameWithType: IEnvelope
  fullName: EventStore.Core.Messaging.IEnvelope
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs
  commentId: T:EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs
  parent: EventStore.Projections.Core.Messages
  name: ProjectionManagementMessage.RunAs
  nameWithType: ProjectionManagementMessage.RunAs
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.RunAs
- uid: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name*
  commentId: Overload:EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
  name: Name
  nameWithType: ProjectionManagementMessage.Command.GetConfig.Name
  fullName: EventStore.Projections.Core.Messages.ProjectionManagementMessage.Command.GetConfig.Name
