### YamlMime:ManagedReference
items:
- uid: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig
  commentId: T:EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig
  id: ProjectionOutputConfig
  parent: EventStore.Projections.Core.Services.Processing
  children:
  - EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
  langs:
  - csharp
  - vb
  name: ProjectionOutputConfig
  nameWithType: ProjectionOutputConfig
  fullName: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig
  type: Class
  source:
    id: ProjectionOutputConfig
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/ProjectionOutputConfig.cs
    startLine: 3
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: 'public class ProjectionOutputConfig : object'
    content.vb: >-
      Public Class ProjectionOutputConfig

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
  commentId: P:EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
  id: ResultStreamName
  parent: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig
  langs:
  - csharp
  - vb
  name: ResultStreamName
  nameWithType: ProjectionOutputConfig.ResultStreamName
  fullName: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
  type: Property
  source:
    id: ResultStreamName
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/ProjectionOutputConfig.cs
    startLine: 5
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public string ResultStreamName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ResultStreamName As String
  overload: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: EventStore.Projections.Core.Services.Processing
  commentId: N:EventStore.Projections.Core.Services.Processing
  name: EventStore.Projections.Core.Services.Processing
  nameWithType: EventStore.Projections.Core.Services.Processing
  fullName: EventStore.Projections.Core.Services.Processing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
  name: ResultStreamName
  nameWithType: ProjectionOutputConfig.ResultStreamName
  fullName: EventStore.Projections.Core.Services.Processing.ProjectionOutputConfig.ResultStreamName
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
