### YamlMime:ManagedReference
items:
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings
  commentId: T:EventStore.ClientAPI.PersistentSubscriptionSettings
  id: PersistentSubscriptionSettings
  parent: EventStore.ClientAPI
  children:
  - EventStore.ClientAPI.PersistentSubscriptionSettings.CheckPointAfter
  - EventStore.ClientAPI.PersistentSubscriptionSettings.Create
  - EventStore.ClientAPI.PersistentSubscriptionSettings.ExtraStatistics
  - EventStore.ClientAPI.PersistentSubscriptionSettings.HistoryBufferSize
  - EventStore.ClientAPI.PersistentSubscriptionSettings.LiveBufferSize
  - EventStore.ClientAPI.PersistentSubscriptionSettings.MaxCheckPointCount
  - EventStore.ClientAPI.PersistentSubscriptionSettings.MaxRetryCount
  - EventStore.ClientAPI.PersistentSubscriptionSettings.MaxSubscriberCount
  - EventStore.ClientAPI.PersistentSubscriptionSettings.MessageTimeout
  - EventStore.ClientAPI.PersistentSubscriptionSettings.MinCheckPointCount
  - EventStore.ClientAPI.PersistentSubscriptionSettings.NamedConsumerStrategy
  - EventStore.ClientAPI.PersistentSubscriptionSettings.ReadBatchSize
  - EventStore.ClientAPI.PersistentSubscriptionSettings.ResolveLinkTos
  - EventStore.ClientAPI.PersistentSubscriptionSettings.StartFrom
  langs:
  - csharp
  - vb
  name: PersistentSubscriptionSettings
  nameWithType: PersistentSubscriptionSettings
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings
  type: Class
  source:
    id: PersistentSubscriptionSettings
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 8
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nRepresents the settings for a <xref href=\"EventStore.ClientAPI.PersistentEventStoreSubscription\" data-throw-if-not-resolved=\"false\"></xref>. You should not use\nthis directly, but instead created via a <xref href=\"EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class PersistentSubscriptionSettings : object'
    content.vb: >-
      Public Class PersistentSubscriptionSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.Create
  commentId: M:EventStore.ClientAPI.PersistentSubscriptionSettings.Create
  id: Create
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: Create()
  nameWithType: PersistentSubscriptionSettings.Create()
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.Create()
  type: Method
  source:
    id: Create
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 13
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nCreates a new <xref href=\"EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder\" data-throw-if-not-resolved=\"false\"></xref> object\n"
  example: []
  syntax:
    content: public static PersistentSubscriptionSettingsBuilder Create()
    return:
      type: EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder
      description: a new <xref href="EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder" data-throw-if-not-resolved="false"></xref> object
    content.vb: Public Shared Function Create As PersistentSubscriptionSettingsBuilder
  overload: EventStore.ClientAPI.PersistentSubscriptionSettings.Create*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.ResolveLinkTos
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.ResolveLinkTos
  id: ResolveLinkTos
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: ResolveLinkTos
  nameWithType: PersistentSubscriptionSettings.ResolveLinkTos
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.ResolveLinkTos
  type: Field
  source:
    id: ResolveLinkTos
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 33
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nWhether the <xref href=\"EventStore.ClientAPI.PersistentEventStoreSubscription\" data-throw-if-not-resolved=\"false\"></xref> should resolve linkTo events to their linked events.\n"
  example: []
  syntax:
    content: public readonly bool ResolveLinkTos
    return:
      type: System.Boolean
    content.vb: Public ReadOnly ResolveLinkTos As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.StartFrom
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.StartFrom
  id: StartFrom
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: StartFrom
  nameWithType: PersistentSubscriptionSettings.StartFrom
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.StartFrom
  type: Field
  source:
    id: StartFrom
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 38
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nWhich event position in the stream the subscription should start from.\n"
  example: []
  syntax:
    content: public readonly long StartFrom
    return:
      type: System.Int64
    content.vb: Public ReadOnly StartFrom As Long
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.ExtraStatistics
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.ExtraStatistics
  id: ExtraStatistics
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: ExtraStatistics
  nameWithType: PersistentSubscriptionSettings.ExtraStatistics
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.ExtraStatistics
  type: Field
  source:
    id: ExtraStatistics
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 43
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nWhether to track latency statistics on this subscription.\n"
  example: []
  syntax:
    content: public readonly bool ExtraStatistics
    return:
      type: System.Boolean
    content.vb: Public ReadOnly ExtraStatistics As Boolean
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.MessageTimeout
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.MessageTimeout
  id: MessageTimeout
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: MessageTimeout
  nameWithType: PersistentSubscriptionSettings.MessageTimeout
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.MessageTimeout
  type: Field
  source:
    id: MessageTimeout
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 48
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe amount of time after which to consider a message as timedout and retried.\n"
  example: []
  syntax:
    content: public readonly TimeSpan MessageTimeout
    return:
      type: TimeSpan
    content.vb: Public ReadOnly MessageTimeout As TimeSpan
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxRetryCount
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.MaxRetryCount
  id: MaxRetryCount
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: MaxRetryCount
  nameWithType: PersistentSubscriptionSettings.MaxRetryCount
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxRetryCount
  type: Field
  source:
    id: MaxRetryCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 53
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe maximum number of retries (due to timeout) before a message is considered to be parked.\n"
  example: []
  syntax:
    content: public int MaxRetryCount
    return:
      type: System.Int32
    content.vb: Public MaxRetryCount As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.LiveBufferSize
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.LiveBufferSize
  id: LiveBufferSize
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: LiveBufferSize
  nameWithType: PersistentSubscriptionSettings.LiveBufferSize
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.LiveBufferSize
  type: Field
  source:
    id: LiveBufferSize
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 58
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe size of the buffer (in-memory) listening to live messages as they happen before paging occurs.\n"
  example: []
  syntax:
    content: public int LiveBufferSize
    return:
      type: System.Int32
    content.vb: Public LiveBufferSize As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.ReadBatchSize
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.ReadBatchSize
  id: ReadBatchSize
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: ReadBatchSize
  nameWithType: PersistentSubscriptionSettings.ReadBatchSize
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.ReadBatchSize
  type: Field
  source:
    id: ReadBatchSize
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 63
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe number of events read at a time when paging through history.\n"
  example: []
  syntax:
    content: public int ReadBatchSize
    return:
      type: System.Int32
    content.vb: Public ReadBatchSize As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.HistoryBufferSize
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.HistoryBufferSize
  id: HistoryBufferSize
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: HistoryBufferSize
  nameWithType: PersistentSubscriptionSettings.HistoryBufferSize
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.HistoryBufferSize
  type: Field
  source:
    id: HistoryBufferSize
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 68
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe number of events to cache when paging through history.\n"
  example: []
  syntax:
    content: public int HistoryBufferSize
    return:
      type: System.Int32
    content.vb: Public HistoryBufferSize As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.CheckPointAfter
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.CheckPointAfter
  id: CheckPointAfter
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: CheckPointAfter
  nameWithType: PersistentSubscriptionSettings.CheckPointAfter
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.CheckPointAfter
  type: Field
  source:
    id: CheckPointAfter
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 73
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe amount of time to try to checkpoint after.\n"
  example: []
  syntax:
    content: public readonly TimeSpan CheckPointAfter
    return:
      type: TimeSpan
    content.vb: Public ReadOnly CheckPointAfter As TimeSpan
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.MinCheckPointCount
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.MinCheckPointCount
  id: MinCheckPointCount
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: MinCheckPointCount
  nameWithType: PersistentSubscriptionSettings.MinCheckPointCount
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.MinCheckPointCount
  type: Field
  source:
    id: MinCheckPointCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 78
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe minimum number of messages to write to a checkpoint.\n"
  example: []
  syntax:
    content: public readonly int MinCheckPointCount
    return:
      type: System.Int32
    content.vb: Public ReadOnly MinCheckPointCount As Integer
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxCheckPointCount
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.MaxCheckPointCount
  id: MaxCheckPointCount
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: MaxCheckPointCount
  nameWithType: PersistentSubscriptionSettings.MaxCheckPointCount
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxCheckPointCount
  type: Field
  source:
    id: MaxCheckPointCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 83
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe maximum number of messages not checkpointed before forcing a checkpoint.\n"
  example: []
  syntax:
    content: public readonly int MaxCheckPointCount
    return:
      type: System.Int32
    content.vb: Public ReadOnly MaxCheckPointCount As Integer
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxSubscriberCount
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.MaxSubscriberCount
  id: MaxSubscriberCount
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: MaxSubscriberCount
  nameWithType: PersistentSubscriptionSettings.MaxSubscriberCount
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.MaxSubscriberCount
  type: Field
  source:
    id: MaxSubscriberCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 88
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe maximum number of subscribers allowed.\n"
  example: []
  syntax:
    content: public readonly int MaxSubscriberCount
    return:
      type: System.Int32
    content.vb: Public ReadOnly MaxSubscriberCount As Integer
  modifiers.csharp:
  - public
  - readonly
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.NamedConsumerStrategy
  commentId: F:EventStore.ClientAPI.PersistentSubscriptionSettings.NamedConsumerStrategy
  id: NamedConsumerStrategy
  parent: EventStore.ClientAPI.PersistentSubscriptionSettings
  langs:
  - csharp
  - vb
  name: NamedConsumerStrategy
  nameWithType: PersistentSubscriptionSettings.NamedConsumerStrategy
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.NamedConsumerStrategy
  type: Field
  source:
    id: NamedConsumerStrategy
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.ClientAPI/PersistentSubscriptionSettings.cs
    startLine: 93
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe strategy to use for distributing events to client consumers. See <xref href=\"EventStore.ClientAPI.Common.SystemConsumerStrategies\" data-throw-if-not-resolved=\"false\"></xref> for system supported strategies.\n"
  example: []
  syntax:
    content: public string NamedConsumerStrategy
    return:
      type: System.String
    content.vb: Public NamedConsumerStrategy As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: EventStore.ClientAPI.PersistentEventStoreSubscription
  commentId: T:EventStore.ClientAPI.PersistentEventStoreSubscription
  isExternal: true
- uid: EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder
  commentId: T:EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder
  parent: EventStore.ClientAPI
  name: PersistentSubscriptionSettingsBuilder
  nameWithType: PersistentSubscriptionSettingsBuilder
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettingsBuilder
- uid: EventStore.ClientAPI
  commentId: N:EventStore.ClientAPI
  name: EventStore.ClientAPI
  nameWithType: EventStore.ClientAPI
  fullName: EventStore.ClientAPI
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.ClientAPI.PersistentSubscriptionSettings.Create*
  commentId: Overload:EventStore.ClientAPI.PersistentSubscriptionSettings.Create
  name: Create
  nameWithType: PersistentSubscriptionSettings.Create
  fullName: EventStore.ClientAPI.PersistentSubscriptionSettings.Create
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Int64
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: TimeSpan
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: TimeSpan
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventStore.ClientAPI.Common.SystemConsumerStrategies
  commentId: T:EventStore.ClientAPI.Common.SystemConsumerStrategies
  name: SystemConsumerStrategies
  nameWithType: SystemConsumerStrategies
  fullName: EventStore.ClientAPI.Common.SystemConsumerStrategies
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
