### YamlMime:ManagedReference
items:
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  commentId: T:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  id: EmittedStream.WriterConfiguration.StreamMetadata
  parent: EventStore.Projections.Core.Services.Processing
  children:
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor(System.Nullable{System.Int32},System.Nullable{TimeSpan})
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  langs:
  - csharp
  - vb
  name: EmittedStream.WriterConfiguration.StreamMetadata
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  type: Class
  source:
    id: StreamMetadata
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 78
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: 'public class StreamMetadata : object'
    content.vb: >-
      Public Class StreamMetadata
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor(System.Nullable{System.Int32},System.Nullable{TimeSpan})
  commentId: M:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor(System.Nullable{System.Int32},System.Nullable{TimeSpan})
  id: '#ctor(System.Nullable{System.Int32},System.Nullable{TimeSpan})'
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  langs:
  - csharp
  - vb
  name: StreamMetadata(Nullable<Int32>, Nullable<TimeSpan>)
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata(Nullable<Int32>, Nullable<TimeSpan>)
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata(System.Nullable<System.Int32>, System.Nullable<TimeSpan>)
  type: Constructor
  source:
    id: .ctor
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 82
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public StreamMetadata(int? maxCount = null, TimeSpan? maxAge = null)
    parameters:
    - id: maxCount
      type: System.Nullable{System.Int32}
    - id: maxAge
      type: System.Nullable{TimeSpan}
    content.vb: Public Sub New(maxCount As Integer? = Nothing, maxAge As TimeSpan? = Nothing)
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor*
  nameWithType.vb: EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata(Nullable(Of Int32), Nullable(Of TimeSpan))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata(System.Nullable(Of System.Int32), System.Nullable(Of TimeSpan))
  name.vb: StreamMetadata(Nullable(Of Int32), Nullable(Of TimeSpan))
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  id: MaxCount
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  langs:
  - csharp
  - vb
  name: MaxCount
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  type: Property
  source:
    id: MaxCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 87
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public int? MaxCount { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property MaxCount As Integer?
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  id: MaxAge
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  langs:
  - csharp
  - vb
  name: MaxAge
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  type: Property
  source:
    id: MaxAge
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 91
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public TimeSpan? MaxAge { get; }
    parameters: []
    return:
      type: System.Nullable{TimeSpan}
    content.vb: Public ReadOnly Property MaxAge As TimeSpan?
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: EventStore.Projections.Core.Services.Processing
  commentId: N:EventStore.Projections.Core.Services.Processing
  name: EventStore.Projections.Core.Services.Processing
  nameWithType: EventStore.Projections.Core.Services.Processing
  fullName: EventStore.Projections.Core.Services.Processing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.#ctor
  name: StreamMetadata
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.StreamMetadata
- uid: System.Nullable{System.Int32}
  commentId: '!:System.Nullable{System.Int32}'
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullName.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable{TimeSpan}
  commentId: '!:System.Nullable{TimeSpan}'
  definition: System.Nullable`1
  name: Nullable<TimeSpan>
  nameWithType: Nullable<TimeSpan>
  fullName: System.Nullable<TimeSpan>
  nameWithType.vb: Nullable(Of TimeSpan)
  fullName.vb: System.Nullable(Of TimeSpan)
  name.vb: Nullable(Of TimeSpan)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: TimeSpan
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: TimeSpan
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  name: MaxCount
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxCount
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  name: MaxAge
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata.MaxAge
