### YamlMime:ManagedReference
items:
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  commentId: T:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  id: CatchUpSubscriptionFilteredSettings
  parent: EventStore.ClientAPI
  children:
  - EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor(System.Int32,System.Int32,System.Boolean,System.Boolean,System.Int32,System.String)
  - EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.Default
  - EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  langs:
  - csharp
  - vb
  name: CatchUpSubscriptionFilteredSettings
  nameWithType: CatchUpSubscriptionFilteredSettings
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  type: Class
  source:
    remote:
      path: src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: CatchUpSubscriptionFilteredSettings
    path: ../EventStore/src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
    startLine: 4
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  example: []
  syntax:
    content: 'public class CatchUpSubscriptionFilteredSettings : CatchUpSubscriptionSettings'
    content.vb: >-
      Public Class CatchUpSubscriptionFilteredSettings

          Inherits CatchUpSubscriptionSettings
  inheritance:
  - System.Object
  - EventStore.ClientAPI.CatchUpSubscriptionSettings
  inheritedMembers:
  - EventStore.ClientAPI.CatchUpSubscriptionSettings.MaxLiveQueueSize
  - EventStore.ClientAPI.CatchUpSubscriptionSettings.ReadBatchSize
  - EventStore.ClientAPI.CatchUpSubscriptionSettings.VerboseLogging
  - EventStore.ClientAPI.CatchUpSubscriptionSettings.ResolveLinkTos
  - EventStore.ClientAPI.CatchUpSubscriptionSettings.SubscriptionName
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor(System.Int32,System.Int32,System.Boolean,System.Boolean,System.Int32,System.String)
  commentId: M:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor(System.Int32,System.Int32,System.Boolean,System.Boolean,System.Int32,System.String)
  id: '#ctor(System.Int32,System.Int32,System.Boolean,System.Boolean,System.Int32,System.String)'
  parent: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  langs:
  - csharp
  - vb
  name: CatchUpSubscriptionFilteredSettings(Int32, Int32, Boolean, Boolean, Int32, String)
  nameWithType: CatchUpSubscriptionFilteredSettings.CatchUpSubscriptionFilteredSettings(Int32, Int32, Boolean, Boolean, Int32, String)
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.CatchUpSubscriptionFilteredSettings(System.Int32, System.Int32, System.Boolean, System.Boolean, System.Int32, System.String)
  type: Constructor
  source:
    remote:
      path: src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: .ctor
    path: ../EventStore/src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
    startLine: 14
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nConstructs a new <xref href=\"EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public CatchUpSubscriptionFilteredSettings(int maxLiveQueueSize, int readBatchSize, bool verboseLogging, bool resolveLinkTos, int maxSearchWindow, string subscriptionName = "")
    parameters:
    - id: maxLiveQueueSize
      type: System.Int32
      description: ''
    - id: readBatchSize
      type: System.Int32
      description: ''
    - id: verboseLogging
      type: System.Boolean
      description: ''
    - id: resolveLinkTos
      type: System.Boolean
      description: ''
    - id: maxSearchWindow
      type: System.Int32
      description: ''
    - id: subscriptionName
      type: System.String
      description: ''
    content.vb: Public Sub New(maxLiveQueueSize As Integer, readBatchSize As Integer, verboseLogging As Boolean, resolveLinkTos As Boolean, maxSearchWindow As Integer, subscriptionName As String = "")
  overload: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  commentId: P:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  id: MaxSearchWindow
  parent: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  langs:
  - csharp
  - vb
  name: MaxSearchWindow
  nameWithType: CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  type: Property
  source:
    remote:
      path: src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: MaxSearchWindow
    path: ../EventStore/src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
    startLine: 24
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe maximum number of events the server will search through before returning the <xref href=\"EventStore.ClientAPI.AllEventsSlice\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public int MaxSearchWindow { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MaxSearchWindow As Integer
  overload: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.Default
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.Default
  id: Default
  parent: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: CatchUpSubscriptionFilteredSettings.Default
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.Default
  type: Field
  source:
    remote:
      path: src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
      branch: master
      repo: git@github.com:EventStore/EventStore.git
    id: Default
    path: ../EventStore/src/EventStore.ClientAPI/CatchUpSubscriptionFilteredSettings.cs
    startLine: 29
  assemblies:
  - EventStore.ClientAPI
  namespace: EventStore.ClientAPI
  summary: "\nThe default <xref href=\"EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public static readonly CatchUpSubscriptionFilteredSettings Default
    return:
      type: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
    content.vb: Public Shared ReadOnly Default As CatchUpSubscriptionFilteredSettings
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: EventStore.ClientAPI
  commentId: N:EventStore.ClientAPI
  name: EventStore.ClientAPI
  nameWithType: EventStore.ClientAPI
  fullName: EventStore.ClientAPI
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings
  commentId: T:EventStore.ClientAPI.CatchUpSubscriptionSettings
  parent: EventStore.ClientAPI
  name: CatchUpSubscriptionSettings
  nameWithType: CatchUpSubscriptionSettings
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings.MaxLiveQueueSize
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionSettings.MaxLiveQueueSize
  parent: EventStore.ClientAPI.CatchUpSubscriptionSettings
  name: MaxLiveQueueSize
  nameWithType: CatchUpSubscriptionSettings.MaxLiveQueueSize
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings.MaxLiveQueueSize
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings.ReadBatchSize
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionSettings.ReadBatchSize
  parent: EventStore.ClientAPI.CatchUpSubscriptionSettings
  name: ReadBatchSize
  nameWithType: CatchUpSubscriptionSettings.ReadBatchSize
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings.ReadBatchSize
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings.VerboseLogging
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionSettings.VerboseLogging
  parent: EventStore.ClientAPI.CatchUpSubscriptionSettings
  name: VerboseLogging
  nameWithType: CatchUpSubscriptionSettings.VerboseLogging
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings.VerboseLogging
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings.ResolveLinkTos
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionSettings.ResolveLinkTos
  parent: EventStore.ClientAPI.CatchUpSubscriptionSettings
  name: ResolveLinkTos
  nameWithType: CatchUpSubscriptionSettings.ResolveLinkTos
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings.ResolveLinkTos
- uid: EventStore.ClientAPI.CatchUpSubscriptionSettings.SubscriptionName
  commentId: F:EventStore.ClientAPI.CatchUpSubscriptionSettings.SubscriptionName
  parent: EventStore.ClientAPI.CatchUpSubscriptionSettings
  name: SubscriptionName
  nameWithType: CatchUpSubscriptionSettings.SubscriptionName
  fullName: EventStore.ClientAPI.CatchUpSubscriptionSettings.SubscriptionName
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  commentId: T:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
  parent: EventStore.ClientAPI
  name: CatchUpSubscriptionFilteredSettings
  nameWithType: CatchUpSubscriptionFilteredSettings
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor*
  commentId: Overload:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.#ctor
  name: CatchUpSubscriptionFilteredSettings
  nameWithType: CatchUpSubscriptionFilteredSettings.CatchUpSubscriptionFilteredSettings
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.CatchUpSubscriptionFilteredSettings
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: EventStore.ClientAPI.AllEventsSlice
  commentId: T:EventStore.ClientAPI.AllEventsSlice
  name: AllEventsSlice
  nameWithType: AllEventsSlice
  fullName: EventStore.ClientAPI.AllEventsSlice
- uid: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow*
  commentId: Overload:EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  name: MaxSearchWindow
  nameWithType: CatchUpSubscriptionFilteredSettings.MaxSearchWindow
  fullName: EventStore.ClientAPI.CatchUpSubscriptionFilteredSettings.MaxSearchWindow
