name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: ./ # Uses an action in the root directory
      with:
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        config:
          https://gist.githubusercontent.com/jdkato/171186055d382c6065273fe5a7eeeb61/raw/af83f7c389414e824765b67b6b13f1dd418185e4/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
